#pragma once
#include <wx/wx.h>
#include <wx/event.h>

// this is typically in a header: it just declares MY_EVENT event type
wxDECLARE_EVENT(PROCOAN_BUTTON_DOWN, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_SLIDER_MOVEABSOLUTE, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_HSCROLL_MOVEABSOLUTE, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_VSCROLL_MOVEABSOLUTE, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_SLIDER_HOVER, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_SLIDER_HOVER_CLEAR, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_UPDATE_TAB, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_UPDATE_BPMNWINDOW, wxCommandEvent);
wxDECLARE_EVENT(PROCOAN_SLIDER_UPDATETIME, wxCommandEvent);


enum
{
	BUTTON_RECORDER = wxID_HIGHEST + 1, // declares an id which will be used to call our button
	BUTTON_EDITOR = wxID_HIGHEST + 2,
	BUTTON_PLAYER = wxID_HIGHEST + 3,
	BUTTON_SPY = wxID_HIGHEST + 4,
	BUTTON_CLOSE = wxID_HIGHEST + 5,
	BUTTON_MINIMIZE = wxID_HIGHEST + 6,
	BUTTON_PAUSE = wxID_HIGHEST + 7,
	BUTTON_RECORD = wxID_HIGHEST + 8,
	BUTTON_STOP = wxID_HIGHEST + 9,
	BUTTON_MAXIMIZE = wxID_HIGHEST + 10,
	RECORDER_VIDEO_CHECKBOX = wxID_HIGHEST + 11,
	RECORDER_AUDIO_CHECKBOX = wxID_HIGHEST + 12,
	RECORDER_EVENTS_CHECKBOX = wxID_HIGHEST + 13,
	PIC_SLIDER = wxID_HIGHEST + 14,
	EDITOR_FREW = wxID_HIGHEST + 15,
	EDITOR_SREW = wxID_HIGHEST + 16,
	EDITOR_FFWD = wxID_HIGHEST + 17,
	EDITOR_SFWD = wxID_HIGHEST + 18,
	EDITOR_STOP = wxID_HIGHEST + 19,
	EDITOR_PLAY = wxID_HIGHEST + 20,
	EDITOR_ADD_ACTIVTY = wxID_HIGHEST + 21,
	EDITOR_START_SEGMENT = wxID_HIGHEST + 22,
	EDITOR_END_SEGMENT = wxID_HIGHEST + 23,
	EDITOR_COPY_SEGMENT = wxID_HIGHEST + 24,
	EDITOR_CUT_SEGMENT = wxID_HIGHEST + 25,
	EDITOR_PASTE_SEGMENT = wxID_HIGHEST + 26,
	EDITOR_CLEAR_SEGMENT = wxID_HIGHEST + 27,
	EDITOR_BRANCH_SEGMENT = wxID_HIGHEST + 28,
	BPMN_CONTROL_HORIZ_SCROLL = wxID_HIGHEST + 29,
	BPMN_CONTROL_VERT_SCROLL = wxID_HIGHEST + 30,
	IDM_CREATE_SUB_PROCESS = wxID_HIGHEST + 31,
	IDM_MOVE_SUB_PROCESS_ABOVE = wxID_HIGHEST + 32,
	IDM_MOVE_SUB_PROCESS_BELOW = wxID_HIGHEST + 33,
	IDM_MOVE_PROCESS_ABOVE = wxID_HIGHEST + 34,
	IDM_MOVE_LEVEL_UP = wxID_HIGHEST + 35,
	IDM_BRANCH_DELETE = wxID_HIGHEST + 36,
	IDM_EVENT_DELETE = wxID_HIGHEST + 37,
	IDM_EVENT_SYNC = wxID_HIGHEST + 38,
	IDM_BRANCH_RIGHT = wxID_HIGHEST + 39,
	IDM_BRANCH_BOTTOM = wxID_HIGHEST + 0x3a,
	IDM_OPEN_READONLY = wxID_HIGHEST + 0x3b,
	ID_VIDEO_PANEL_NOTEBOOK = wxID_HIGHEST + 0x3c,
	IDM_BRANCH_COPY = wxID_HIGHEST + 0x3d,
	EVENT_NAME_TEXT = wxID_HIGHEST + 0x40,
	EVENT_NAME_DESC = wxID_HIGHEST + 0x41,
	EVENT_ACTION_GROUP = wxID_HIGHEST + 0x42,
	EVENT_ACTION_SUBGROUP = wxID_HIGHEST + 0x43,
	EVENT_ACTION_TYPE = wxID_HIGHEST + 0x44,
	EVENT_ACTION = wxID_HIGHEST + 0x45,
	EVENT_SAVE = wxID_HIGHEST + 0x46,
	ID_ACTION_TAB = wxID_HIGHEST + 0x47,
	ID_BPMN_CONTROL = wxID_HIGHEST + 0x48,
	ID_INFO_TAB = wxID_HIGHEST + 0x49,
	TOOLBAR_OPEN_PRIMARY = wxID_HIGHEST + 0x4a,
	TOOLBAR_OPEN_SECONDARY = wxID_HIGHEST + 0x4b,
	TOOLBAR_CLOSE_FILE = wxID_HIGHEST + 0x4c,
	TOOLBAR_SWITCH_PANEL = wxID_HIGHEST + 0x4d,
	TOOLBAR_SHOW_TAB = wxID_HIGHEST + 0x4e,
	TOOLBAR_SHOW_LEFT = wxID_HIGHEST + 0x4f,
	TOOLBAR_SHOW_TOP = wxID_HIGHEST + 0x50,
	TOOLBAR_SHOW_RIGHT = wxID_HIGHEST + 0x51,
	TOOLBAR_SHOW_BOTTOM = wxID_HIGHEST + 0x52,
	TOOLBAR_SHOW_SUBTITLE = wxID_HIGHEST + 0x53,
	TOOLBAR_SHOW_DESCRIPTION = wxID_HIGHEST + 0x54,
	TOOLBAR_SHOW_ZOOM = wxID_HIGHEST + 0x55,
	TOOLBAR_REPORT_SOP = wxID_HIGHEST + 0x56,
	TOOLBAR_MANAGE_SCENARIO = wxID_HIGHEST + 0x57,
	TOOLBAR_RECORDING_INFO = wxID_HIGHEST + 0x59,
	TOOLBAR_SHOW_MULTI_MONITOR = wxID_HIGHEST + 0x5a,
	TOOLBAR_SHOW_ACTIVE_MONITOR = wxID_HIGHEST + 0x5b,
	TOOLBAR_SCENARIO_CHOICE = wxID_HIGHEST + 0x5c,
	TOOLBAR_PLAY_SCENARIO = wxID_HIGHEST + 0x5d,
	TOOLBAR_BPMN_BRANCH_BOTTOM = wxID_HIGHEST + 0x60,
	TOOLBAR_BPMN_BRANCH_RIGHT = wxID_HIGHEST + 0x61,
	TOOLBAR_BPMN_CREATE_SUBPROCESS = wxID_HIGHEST + 0x62,
	TOOLBAR_BPMN_DELETE_BRANCH = wxID_HIGHEST + 0x63,
	TOOLBAR_BPMN_DELETE_EVENT = wxID_HIGHEST + 0x64,
	TOOLBAR_BPMN_UP_LEVEL = wxID_HIGHEST + 0x65,
	TOOLBAR_BPMN_MOVE_PROCESS_BELOW = wxID_HIGHEST + 0x66,
	TOOLBAR_BPMN_MOVE_SUBPROCESS_ABOVE = wxID_HIGHEST + 0x67,
	TOOLBAR_BPMN_MOVE_SUBPROCESS_BELOW = wxID_HIGHEST + 0x68,
	TOOLBAR_BPMN_SYNC_VIDEO = wxID_HIGHEST + 0x69,

	RECORDER_SETUP_SELECT_DIR = wxID_HIGHEST + 0x70,
	RECORDER_SETUP_START = wxID_HIGHEST + 0x71,
	RECORDER_SETUP_SAVE = wxID_HIGHEST + 0x72,
	RECORDER_SETUP_CLOSE = wxID_HIGHEST + 0x73,

	SCENARIO_LISTBOX = wxID_HIGHEST + 0x80,
	SCENARIO_PLAYBTN = wxID_HIGHEST + 0x81,
	SCENARIO_SELECTBTN = wxID_HIGHEST + 0x82,
	SCENARIO_NEWBTN = wxID_HIGHEST + 0x83,
	SCENARIO_SAVEBTN = wxID_HIGHEST + 0x84,
	SCENARIO_CANCELBTN = wxID_HIGHEST + 0x85,
	SCENARIO_CLOSEBTN = wxID_HIGHEST + 0x86,
};