#pragma once

struct keyAnnoations {
	int index;
	const char *baseAnnotation;
	const char *controlAnnotation;
	const char *shiftAnnotation;
	const char *altAnnotation;
	const char *controlAltAnnotation;
	const char *controlShiftAnnotation;
	const char *altShiftAnnotation;
	const char *controlAltShiftAnnotation;
} keyAnnotationTable[] =
{
{1, "Press Backspace", "Go Back Word", "Mark Text Block", "Press ALT+BKSP", "Press CTRL+ALT+BKSP", "Press CTRL+SHIFT+BKSP", "Press ALT+SHIFT+BKSP", "Press CTRL+ALT+SHIFT+BKSP"},
{ 2,"Press Tab","Press CTRL+TAB","Press SHIFT+TAB","Switch Application","Press CTRL+ALT+TAB","Press CTRL+SHIFT+TAB","Press ALT+SHIFT+TAB","Press CTRL+ALT+SHIFT+TAB" },
{ 3,"Press Enter","Press CTRL+Enter","Press SHIFT+Enter","Press ALT+Enter","Press CTRL+ALT+Enter","Press CTRL+SHIFT+Enter","Press ALT+SHIFT+Enter","Press CTRL+ALT+SHIFT+Enter" },
{ 4,"","","","","","","","" },
{ 5,"","","","","","","","" },
{ 6,"Press Page UP","Go to Previous Page","Mark Text Block","Press  ALT+PAGEUP","Press CTRL+ALT+PAGEUP","Press CTRL+SHIFT+PAGEUP","Press ALT+SHIFT+PAGEUP","Press CTRL+ALT+SHIFTPAGEUP" },
{ 7,"Press Page Down","Go to Next Page","Mark Text Block","Press  ALT+PAGEDN","Press CTRL+ALT+PAGEDN","Press CTRL+SHIFT+PAGEDN","Press ALT+SHIFT+PAGEDN","Press CTRL+ALT+SHIFTPAGEDN" },
{ 8,"Press End","Go to End","Mark Text Block","Press  ALT+END","Press CTRL+ALT+END","Press CTRL+SHIFT+END","Press ALT+SHIFT+END","Press CTRL+ALT+SHIFTEND" },
{ 9,"Press Home","Go to Start","Mark Text Block","Press  ALT+HOME","Press CTRL+ALT+HOME","Press CTRL+SHIFT+HOME","Press ALT+SHIFT+HOME","Press CTRL+ALT+SHIFTHOME" },
{ 10,"Go Back","Go to Start of Line","Mark Text Block","Press  ALT+LEFT","Press CTRL+ALT+LEFT","Press CTRL+SHIFT+LEFT","Press ALT+SHIFT+LEFT","Press CTRL+ALT+SHIFTLEFT" },
{ 11,"Go Previous","Go to Previous Line","Mark Text Block","Press  ALT+UP","Press CTRL+ALT+UP","Press CTRL+SHIFT+UP","Press ALT+SHIFT+UP","Press CTRL+ALT+SHIFTUP" },
{ 12,"Go Forward","Go to Next Word","Mark Text Block","Press  ALT+RIGHT","Press CTRL+ALT+RIGHT","Press CTRL+SHIFT+RIGHT","Press ALT+SHIFT+RIGHT","Press CTRL+ALT+SHIFTRIGHT" },
{ 13,"Go Next","Go To Next Line","Mark Text Block","Press  ALT+DOWN","Press CTRL+ALT+DOWN","Press CTRL+SHIFT+DOWN","Press ALT+SHIFT+DOWN","Press CTRL+ALT+SHIFTDOWN" },
{ 14,"Press Print Key","Press  CTRL+PRINT","Press SHIFT+PRINT","Press  ALT+PRINT","Press CTRL+ALT+PRINT","Press CTRL+SHIFT+PRINT","Press ALT+SHIFT+PRINT","Press CTRL+ALT+SHIFTPRINT" },
{ 15,"Print Screen","Press  CTRL+PRINTSCREEN","Press SHIFT+PRINTSCREEN","Press  ALT+PRINTSCREEN","Press CTRL+ALT+PRINTSCREEN","Press CTRL+SHIFT+PRINTSCREEN","Press ALT+SHIFT+PRINTSCREEN","Press CTRL+ALT+SHIFTPRINTSCREEN" },
{ 16,"Press 0","Press  CTRL+NUM0","Press 0","Press  ALT+NUM0","Press CTRL+ALT+NUM0","Press CTRL+SHIFT+NUM0","Press ALT+SHIFT+NUM0","Press CTRL+ALT+SHIFTNUM0" },
{ 17,"Press 1","Press  CTRL+NUM1","Press 0","Press  ALT+NUM1","Press CTRL+ALT+NUM1","Press CTRL+SHIFT+NUM1","Press ALT+SHIFT+NUM1","Press CTRL+ALT+SHIFTNUM1" },
{ 18,"Press 2","Press  CTRL+NUM2","Press 0","Press  ALT+NUM2","Press CTRL+ALT+NUM2","Press CTRL+SHIFT+NUM2","Press ALT+SHIFT+NUM2","Press CTRL+ALT+SHIFTNUM2" },
{ 19,"Press 3","Press  CTRL+NUM3","Press 0","Press  ALT+NUM3","Press CTRL+ALT+NUM3","Press CTRL+SHIFT+NUM3","Press ALT+SHIFT+NUM3","Press CTRL+ALT+SHIFTNUM3" },
{ 20,"Press 4","Press  CTRL+NUM4","Press 0","Press  ALT+NUM4","Press CTRL+ALT+NUM4","Press CTRL+SHIFT+NUM4","Press ALT+SHIFT+NUM4","Press CTRL+ALT+SHIFTNUM4" },
{ 21,"Press 5","Press  CTRL+NUM5","Press 0","Press  ALT+NUM5","Press CTRL+ALT+NUM5","Press CTRL+SHIFT+NUM5","Press ALT+SHIFT+NUM5","Press CTRL+ALT+SHIFTNUM5" },
{ 22,"Press 6","Press  CTRL+NUM6","Press 0","Press  ALT+NUM6","Press CTRL+ALT+NUM6","Press CTRL+SHIFT+NUM6","Press ALT+SHIFT+NUM6","Press CTRL+ALT+SHIFTNUM6" },
{ 23,"Press 7","Press  CTRL+NUM7","Press 0","Press  ALT+NUM7","Press CTRL+ALT+NUM7","Press CTRL+SHIFT+NUM7","Press ALT+SHIFT+NUM7","Press CTRL+ALT+SHIFTNUM7" },
{ 24,"Press 8","Press  CTRL+NUM8","Press 0","Press  ALT+NUM8","Press CTRL+ALT+NUM8","Press CTRL+SHIFT+NUM8","Press ALT+SHIFT+NUM8","Press CTRL+ALT+SHIFTNUM8" },
{ 25,"Press 9","Press  CTRL+NUM9","Press 0","Press  ALT+NUM9","Press CTRL+ALT+NUM9","Press CTRL+SHIFT+NUM9","Press ALT+SHIFT+NUM9","Press CTRL+ALT+SHIFTNUM9" },
{ 26,"Press A","Press  CTRL+A ","Press A","Press  ALT+A ","Press CTRL+ALT+A ","Press CTRL+SHIFT+A ","Press ALT+SHIFT+A ","Press CTRL+ALT+SHIFTA " },
{ 27,"Press B","Press  CTRL+B ","Press B","Press  ALT+B ","Press CTRL+ALT+B ","Press CTRL+SHIFT+B ","Press ALT+SHIFT+B ","Press CTRL+ALT+SHIFTB " },
{ 28,"Press C","Copy Marked Text","Press C","Press  ALT+C ","Press CTRL+ALT+C ","Press CTRL+SHIFT+C ","Press ALT+SHIFT+C ","Press CTRL+ALT+SHIFTC " },
{ 29,"Press D","Press  CTRL+D ","Press D","Press  ALT+D ","Press CTRL+ALT+D ","Press CTRL+SHIFT+D ","Press ALT+SHIFT+D ","Press CTRL+ALT+SHIFTD " },
{ 30,"Press E","Press  CTRL+E ","Press E","Press  ALT+E ","Press CTRL+ALT+E ","Press CTRL+SHIFT+E ","Press ALT+SHIFT+E ","Press CTRL+ALT+SHIFTE " },
{ 31,"Press F","Press  CTRL+F ","Press F","Press  ALT+F ","Press CTRL+ALT+F ","Press CTRL+SHIFT+F ","Press ALT+SHIFT+F ","Press CTRL+ALT+SHIFTF " },
{ 32,"Press G","Press  CTRL+G ","Press G","Press  ALT+G ","Press CTRL+ALT+G ","Press CTRL+SHIFT+G ","Press ALT+SHIFT+G ","Press CTRL+ALT+SHIFTG " },
{ 33,"Press H","Press  CTRL+H ","Press H","Press  ALT+H ","Press CTRL+ALT+H ","Press CTRL+SHIFT+H ","Press ALT+SHIFT+H ","Press CTRL+ALT+SHIFTH " },
{ 34,"Press I","Press  CTRL+I ","Press I","Press  ALT+I ","Press CTRL+ALT+I ","Press CTRL+SHIFT+I ","Press ALT+SHIFT+I ","Press CTRL+ALT+SHIFTI " },
{ 35,"Press J","Press  CTRL+J ","Press J","Press  ALT+J ","Press CTRL+ALT+J ","Press CTRL+SHIFT+J ","Press ALT+SHIFT+J ","Press CTRL+ALT+SHIFTJ " },
{ 36,"Press K","Press  CTRL+K ","Press K","Press  ALT+K ","Press CTRL+ALT+K ","Press CTRL+SHIFT+K ","Press ALT+SHIFT+K ","Press CTRL+ALT+SHIFTK " },
{ 37,"Press L","Press  CTRL+L ","Press L","Press  ALT+L ","Press CTRL+ALT+L ","Press CTRL+SHIFT+L ","Press ALT+SHIFT+L ","Press CTRL+ALT+SHIFTL " },
{ 38,"Press M","Press  CTRL+M ","Press M","Press  ALT+M ","Press CTRL+ALT+M ","Press CTRL+SHIFT+M ","Press ALT+SHIFT+M ","Press CTRL+ALT+SHIFTM " },
{ 39,"Press N","Press  CTRL+N ","Press N","Press  ALT+N ","Press CTRL+ALT+N ","Press CTRL+SHIFT+N ","Press ALT+SHIFT+N ","Press CTRL+ALT+SHIFTN " },
{ 40,"Press O","Press  CTRL+O ","Press O","Press  ALT+O ","Press CTRL+ALT+O ","Press CTRL+SHIFT+O ","Press ALT+SHIFT+O ","Press CTRL+ALT+SHIFTO " },
{ 41,"Press P","Press  CTRL+P ","Press P","Press  ALT+P ","Press CTRL+ALT+P ","Press CTRL+SHIFT+P ","Press ALT+SHIFT+P ","Press CTRL+ALT+SHIFTP " },
{ 42,"Press Q","Press  CTRL+Q ","Press Q","Press  ALT+Q ","Press CTRL+ALT+Q ","Press CTRL+SHIFT+Q ","Press ALT+SHIFT+Q ","Press CTRL+ALT+SHIFTQ " },
{ 43,"Press R","Press  CTRL+R ","Press R","Press  ALT+R ","Press CTRL+ALT+R ","Press CTRL+SHIFT+R ","Press ALT+SHIFT+R ","Press CTRL+ALT+SHIFTR " },
{ 44,"Press S","Press  CTRL+S ","Press S","Press  ALT+S ","Press CTRL+ALT+S ","Press CTRL+SHIFT+S ","Press ALT+SHIFT+S ","Press CTRL+ALT+SHIFTS " },
{ 45,"Press T","Press  CTRL+T ","Press T","Press  ALT+T ","Press CTRL+ALT+T ","Press CTRL+SHIFT+T ","Press ALT+SHIFT+T ","Press CTRL+ALT+SHIFTT " },
{ 46,"Press U","Press  CTRL+U ","Press U","Press  ALT+U ","Press CTRL+ALT+U ","Press CTRL+SHIFT+U ","Press ALT+SHIFT+U ","Press CTRL+ALT+SHIFTU " },
{ 47,"Press V","Paste Marked Text","Press V","Press  ALT+V ","Press CTRL+ALT+V ","Press CTRL+SHIFT+V ","Press ALT+SHIFT+V ","Press CTRL+ALT+SHIFTV " },
{ 48,"Press W","Press  CTRL+W ","Press W","Press  ALT+W ","Press CTRL+ALT+W ","Press CTRL+SHIFT+W ","Press ALT+SHIFT+W ","Press CTRL+ALT+SHIFTW " },
{ 49,"Press X","Delete Marked Text","Press X","Press  ALT+X ","Press CTRL+ALT+X ","Press CTRL+SHIFT+X ","Press ALT+SHIFT+X ","Press CTRL+ALT+SHIFTX " },
{ 50,"Press Y","Press  CTRL+Y ","Press Y","Press  ALT+Y ","Press CTRL+ALT+Y ","Press CTRL+SHIFT+Y ","Press ALT+SHIFT+Y ","Press CTRL+ALT+SHIFTY " },
{ 51,"Press Z","Press  CTRL+Z ","Press Z","Press  ALT+Z ","Press CTRL+ALT+Z ","Press CTRL+SHIFT+Z ","Press ALT+SHIFT+Z ","Press CTRL+ALT+SHIFTZ " },
{ 52,"Press Windows Key","Press  CTRL+WINKEY","","Press  ALT+WINKEY","Press CTRL+ALT+WINKEY","Press CTRL+SHIFT+WINKEY","Press ALT+SHIFT+WINKEY","Press CTRL+ALT+SHIFTWINKEY" },
{ 53,"Press Windows Key","Press  CTRL+WINKEY","","Press  ALT+WINKEY","Press CTRL+ALT+WINKEY","Press CTRL+SHIFT+WINKEY","Press ALT+SHIFT+WINKEY","Press CTRL+ALT+SHIFTWINKEY" },
{ 54,"Press 0","Press  CTRL+NUM0","","Press  ALT+NUM0","Press CTRL+ALT+NUM0","Press CTRL+SHIFT+NUM0","Press ALT+SHIFT+NUM0","Press CTRL+ALT+SHIFTNUM0" },
{ 55,"Press 1","Press  CTRL+NUM1","","Press  ALT+NUM1","Press CTRL+ALT+NUM1","Press CTRL+SHIFT+NUM1","Press ALT+SHIFT+NUM1","Press CTRL+ALT+SHIFTNUM1" },
{ 56,"Press 2","Press  CTRL+NUM2","","Press  ALT+NUM2","Press CTRL+ALT+NUM2","Press CTRL+SHIFT+NUM2","Press ALT+SHIFT+NUM2","Press CTRL+ALT+SHIFTNUM2" },
{ 57,"Press 3","Press  CTRL+NUM3","","Press  ALT+NUM3","Press CTRL+ALT+NUM3","Press CTRL+SHIFT+NUM3","Press ALT+SHIFT+NUM3","Press CTRL+ALT+SHIFTNUM3" },
{ 58,"Press 4","Press  CTRL+NUM4","","Press  ALT+NUM4","Press CTRL+ALT+NUM4","Press CTRL+SHIFT+NUM4","Press ALT+SHIFT+NUM4","Press CTRL+ALT+SHIFTNUM4" },
{ 59,"Press 5","Press  CTRL+NUM5","","Press  ALT+NUM5","Press CTRL+ALT+NUM5","Press CTRL+SHIFT+NUM5","Press ALT+SHIFT+NUM5","Press CTRL+ALT+SHIFTNUM5" },
{ 60,"Press 6","Press  CTRL+NUM6","","Press  ALT+NUM6","Press CTRL+ALT+NUM6","Press CTRL+SHIFT+NUM6","Press ALT+SHIFT+NUM6","Press CTRL+ALT+SHIFTNUM6" },
{ 61,"Press 7","Press  CTRL+NUM7","","Press  ALT+NUM7","Press CTRL+ALT+NUM7","Press CTRL+SHIFT+NUM7","Press ALT+SHIFT+NUM7","Press CTRL+ALT+SHIFTNUM7" },
{ 62,"Press 8","Press  CTRL+NUM8","","Press  ALT+NUM8","Press CTRL+ALT+NUM8","Press CTRL+SHIFT+NUM8","Press ALT+SHIFT+NUM8","Press CTRL+ALT+SHIFTNUM8" },
{ 63,"Press 9","Press  CTRL+NUM9","","Press  ALT+NUM9","Press CTRL+ALT+NUM9","Press CTRL+SHIFT+NUM9","Press ALT+SHIFT+NUM9","Press CTRL+ALT+SHIFTNUM9" },
{ 64,"Press F1","Press  CTRL+F1","","Press  ALT+F1","Press CTRL+ALT+F1","Press CTRL+SHIFT+F1","Press ALT+SHIFT+F1","Press CTRL+ALT+SHIFTF1" },
{ 65,"Press F2","Press  CTRL+F2","","Press  ALT+F2","Press CTRL+ALT+F2","Press CTRL+SHIFT+F2","Press ALT+SHIFT+F2","Press CTRL+ALT+SHIFTF2" },
{ 66,"Press F3","Press  CTRL+F3","","Press  ALT+F3","Press CTRL+ALT+F3","Press CTRL+SHIFT+F3","Press ALT+SHIFT+F3","Press CTRL+ALT+SHIFTF3" },
{ 67,"Press F4","Press  CTRL+F4","","Press  ALT+F4","Press CTRL+ALT+F4","Press CTRL+SHIFT+F4","Press ALT+SHIFT+F4","Press CTRL+ALT+SHIFTF4" },
{ 68,"Press F5","Press  CTRL+F5","","Press  ALT+F5","Press CTRL+ALT+F5","Press CTRL+SHIFT+F5","Press ALT+SHIFT+F5","Press CTRL+ALT+SHIFTF5" },
{ 69,"Press F6","Press  CTRL+F6","","Press  ALT+F6","Press CTRL+ALT+F6","Press CTRL+SHIFT+F6","Press ALT+SHIFT+F6","Press CTRL+ALT+SHIFTF6" },
{ 70,"Press F7","Press  CTRL+F7","","Press  ALT+F7","Press CTRL+ALT+F7","Press CTRL+SHIFT+F7","Press ALT+SHIFT+F7","Press CTRL+ALT+SHIFTF7" },
{ 71,"Press F8","Press  CTRL+F8","","Press  ALT+F8","Press CTRL+ALT+F8","Press CTRL+SHIFT+F8","Press ALT+SHIFT+F8","Press CTRL+ALT+SHIFTF8" },
{ 72,"Press F9","Press  CTRL+F9","","Press  ALT+F9","Press CTRL+ALT+F9","Press CTRL+SHIFT+F9","Press ALT+SHIFT+F9","Press CTRL+ALT+SHIFTF9" },
{ 73,"Press F10","Press  CTRL+F10","","Press  ALT+F10","Press CTRL+ALT+F10","Press CTRL+SHIFT+F10","Press ALT+SHIFT+F10","Press CTRL+ALT+SHIFTF10" },
{ 74,"Press F11","Press  CTRL+F11","","Press  ALT+F11","Press CTRL+ALT+F11","Press CTRL+SHIFT+F11","Press ALT+SHIFT+F11","Press CTRL+ALT+SHIFTF11" },
{ 75,"Press F12","Press  CTRL+F12","","Press  ALT+F12","Press CTRL+ALT+F12","Press CTRL+SHIFT+F12","Press ALT+SHIFT+F12","Press CTRL+ALT+SHIFTF12" },
{ 76,"Press F13","Press  CTRL+F13","","Press  ALT+F13","Press CTRL+ALT+F13","Press CTRL+SHIFT+F13","Press ALT+SHIFT+F13","Press CTRL+ALT+SHIFTF13" },
{ 77,"Press F14","Press  CTRL+F14","","Press  ALT+F14","Press CTRL+ALT+F14","Press CTRL+SHIFT+F14","Press ALT+SHIFT+F14","Press CTRL+ALT+SHIFTF14" },
{ 78,"Press F15","Press  CTRL+F15","","Press  ALT+F15","Press CTRL+ALT+F15","Press CTRL+SHIFT+F15","Press ALT+SHIFT+F15","Press CTRL+ALT+SHIFTF15" },
{ 79,"Press F16","Press  CTRL+F16","","Press  ALT+F16","Press CTRL+ALT+F16","Press CTRL+SHIFT+F16","Press ALT+SHIFT+F16","Press CTRL+ALT+SHIFTF16" },
{ 80,"Press F17","Press  CTRL+F17","","Press  ALT+F17","Press CTRL+ALT+F17","Press CTRL+SHIFT+F17","Press ALT+SHIFT+F17","Press CTRL+ALT+SHIFTF17" },
{ 81,"Press F18","Press  CTRL+F18","","Press  ALT+F18","Press CTRL+ALT+F18","Press CTRL+SHIFT+F18","Press ALT+SHIFT+F18","Press CTRL+ALT+SHIFTF18" },
{ 82,"Press F19","Press  CTRL+F19","","Press  ALT+F19","Press CTRL+ALT+F19","Press CTRL+SHIFT+F19","Press ALT+SHIFT+F19","Press CTRL+ALT+SHIFTF19" },
{ 83,"Press F20","Press  CTRL+F20","","Press  ALT+F20","Press CTRL+ALT+F20","Press CTRL+SHIFT+F20","Press ALT+SHIFT+F20","Press CTRL+ALT+SHIFTF20" },
{ 84,"Press F21","Press  CTRL+F21","","Press  ALT+F21","Press CTRL+ALT+F21","Press CTRL+SHIFT+F21","Press ALT+SHIFT+F21","Press CTRL+ALT+SHIFTF21" },
{ 85,"Press F22","Press  CTRL+F22","","Press  ALT+F22","Press CTRL+ALT+F22","Press CTRL+SHIFT+F22","Press ALT+SHIFT+F22","Press CTRL+ALT+SHIFTF22" },
{ 86,"Press F23","Press  CTRL+F23","","Press  ALT+F23","Press CTRL+ALT+F23","Press CTRL+SHIFT+F23","Press ALT+SHIFT+F23","Press CTRL+ALT+SHIFTF23" },
{ 87,"Press F24","Press  CTRL+F24","","Press  ALT+F24","Press CTRL+ALT+F24","Press CTRL+SHIFT+F24","Press ALT+SHIFT+F24","Press CTRL+ALT+SHIFTF24" },
{ 88,"","","","","","","","" },
{ 89,"","","","","","","","" },
{ 90,"","","","","","","","" },
{ 91,"","","","","","","","" },
{ 92,"","","","","","","","" },
{ 93,"","","","","","","","" },
{ 94,"","","","","","","","" }
};